# Use an official nginx image as the base
FROM nginx:latest

# Copy the local frontend code (including index.html) to the container's working directory
COPY . /usr/share/nginx/html

# Expose port 80
EXPOSE 80
